FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir uv
RUN uv sync --frozen

COPY app ./app
COPY data ./data
COPY chroma_db ./chroma_db

EXPOSE 8501

CMD ["sh", "-c", "uv run streamlit run app/frontend/app.py --server.address=0.0.0.0 --server.port=${PORT:-8501}"]